### ISSUE TITLE
Error Call to undefined function GuzzleHttp\Psr7\parse_query()

### ISSUE THREAD

**Issue by w3spi5** [calliostro/php-discogs-api#3]
PHP version: 8.1.6
Laravel 10.39.0
cURL version: 8.4.0

Description
While doing a simple search after passed OAuth, and so, being authenticated  :

    $response = $client->search([
        'q' => 'Meagashira'
    ]);

It throws an Error "Call to undefined function GuzzleHttp\Psr7\parse_query()".

According to my research, I found this issue on GuzzleHTTP :
https://github.com/guzzle/guzzle/issues/2740

Then this PR : https://github.com/guzzle/psr7/pull/345 mentionning "parse_query | Query::parse", I think problem seems to come from  guzzle/oauth-subscriber package.

It has been fixed on tag 0.6.0, you can find this below : 
https://github.com/guzzle/oauth-subscriber/blob/8d6cab29f8397e5712d00a383eeead36108a3c1f/src/Oauth1.php#L107

I know this is a Guzzle error, but maybe you can force the use of package version 0.6.0 in your dependancies.

**Comment by w3spi5** [comment]
@calliostro Please merge the provided PR asap

**Comment by calliostro** [comment]
Thank you for the investigation. The new version v2.0.4 is now released.
